### ISSUE TITLE
cmake errors when using Ubuntu 16.04

### ISSUE THREAD

**Issue by zengletian1491** [OpenVSLAM-Community/openvslam#109]
**I compile openvslam as the installation instructions on https://openvslam-community.readthedocs.io/en/latest/installation.html.

**The instructions in CMakeLists.txt in openvslam/test** 
download_project(PROJ googletest
                 URL https://github.com/google/googletest/archive/release-1.10.0.tar.gz
                 URL_HASH SHA1=9c89be7df9c5e8cb0bc20b3c4b39bf7e82686770
                 DOWNLOAD_NO_PROGRESS YES)

**does not work, and I modify it as** 

download_project(PROJ googletest
                 URL https://github.com/google/googletest/releases/tag/release-1.10.0/release-1.10.0.tar.gz
                 URL_HASH SHA1=da39a3ee5e6b4b0d3255bfef95601890afd80709
                 DOWNLOAD_NO_PROGRESS YES)**

**Errors occur when I type in the following instructions:**

zeng@zeng-System-Product-Name:/media/zeng/work/openvslam/build$ cmake \
>     -DUSE_PANGOLIN_VIEWER=ON \
>     -DINSTALL_PANGOLIN_VIEWER=ON \
>     -DUSE_SOCKET_PUBLISHER=OFF \
>     -DUSE_STACK_TRACE_LOGGER=ON \
>     -DBUILD_TESTS=ON \
>     -DBUILD_EXAMPLES=ON \
>     ..
-- Build type: Release
-- ccache: Enabled
-- Address/Memory sanitizer: DISABLED
-- Architecture-aware optimization: DISABLED
-- Found OpenMP_C: -fopenmp  
-- Found OpenMP_CXX: -fopenmp  
-- Found OpenMP: TRUE   
-- Use OpenCV 3.4.1
CMake Warning (dev) at /usr/local/share/cmake-3.15/Modules/FindOpenGL.cmake:275 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.15/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /usr/local/lib/cmake/g2o/g2oConfig.cmake:4 (find_dependency)
  src/openvslam/CMakeLists.txt:10 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Failed to find CXSparse - Could not find CXSparse include directory, set CXSPARSE_INCLUDE_DIR to directory containing cs.h
-- Found AMD library: /usr/lib/x86_64-linux-gnu/libamd.so
-- Found AMD header in: /usr/include/suitesparse
-- Found CAMD library: /usr/lib/x86_64-linux-gnu/libcamd.so
-- Found CAMD header in: /usr/include/suitesparse
-- Found COLAMD library: /usr/lib/x86_64-linux-gnu/libcolamd.so
-- Found COLAMD header in: /usr/include/suitesparse
-- Found CCOLAMD library: /usr/lib/x86_64-linux-gnu/libccolamd.so
-- Found CCOLAMD header in: /usr/include/suitesparse
-- Found SuiteSparse_config library: /usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so
-- Found SuiteSparse_config header in: /usr/include/suitesparse
-- Adding librt: /usr/lib/x86_64-linux-gnu/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS library: /usr/local/lib/libmetis.so.
-- OpenMP: DISABLED
-- SSE3 for ORB extraction: DISABLED
-- SSE for floating-point operation: DISABLED
-- BoW framework: FBoW (found in /usr/local/include)
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Stack trace logger: ENABLED
-- Google Perftools: DISABLED
-- Viewer for examples: PangolinViewer
-- Downloading/updating googletest
-- Configuring done
-- Generating done
-- Build files have been written to: /media/zeng/work/openvslam/build/googletest-download
Scanning dependencies of target googletest-download
[ 11%] Performing download step (download, verify and extract) for 'googletest-download'
-- verifying file...
       file='/media/zeng/work/openvslam/build/googletest-download/googletest-download-prefix/src/release-1.10.0.tar.gz'
-- File already exists and hash match (skip download):
  file='/media/zeng/work/openvslam/build/googletest-download/googletest-download-prefix/src/release-1.10.0.tar.gz'
  SHA1='da39a3ee5e6b4b0d3255bfef95601890afd80709'
-- extracting...
     src='/media/zeng/work/openvslam/build/googletest-download/googletest-download-prefix/src/release-1.10.0.tar.gz'
     dst='/media/zeng/work/openvslam/build/googletest-src'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 22%] No patch step for 'googletest-download'
[ 33%] No update step for 'googletest-download'
[ 44%] No configure step for 'googletest-download'
[ 55%] No build step for 'googletest-download'
[ 66%] No install step for 'googletest-download'
[ 77%] No test step for 'googletest-download'
[ 88%] Completed 'googletest-download'
[100%] Built target googletest-download
CMake Error at test/CMakeLists.txt:12 (add_subdirectory):
  The source directory

    /media/zeng/work/openvslam/build/googletest-src

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/media/zeng/work/openvslam/build/CMakeFiles/CMakeOutput.log".
See also "/media/zeng/work/openvslam/build/CMakeFiles/CMakeError.log".

Could you please give me some suggestions?Thank you in advance.

**Comment by ymd-stella** [comment]
Ask at https://github.com/OpenVSLAM-Community/openvslam/discussions.
