### ISSUE TITLE
Add debug level log to relocalizer.cc

### ISSUE THREAD

**Issue by ymd-stella** [OpenVSLAM-Community/openvslam#141]
Display the following as a debug level log

1. Number of candidate keyframes
2. ID of the rejected keyframe candidate and the reason why it was rejected

For more information on how to output logs, please refer to the following:
https://github.com/OpenVSLAM-Community/openvslam/blob/main/src/openvslam/module/frame_tracker.cc#L102

**Comment by jeffin07** [comment]
@ymd-stella I would like to work on this issue can you please guide me ?

**Comment by ymd-stella** [comment]
@jeffin07 Description has been updated.
