### ISSUE TITLE
Describes the rough flow of the relocalization process

### ISSUE THREAD

**Issue by ymd-stella** [OpenVSLAM-Community/openvslam#142]

**Comment by jeffin07** [comment]
@ymd-stella  does  the rough workflow documentation follows the format of the docs folder (.rst format) ?

**Comment by ymd-stella** [comment]
> Can you please tell me What do you mean the "rough flow" of relocalization process.

For example, it is something like the following:

https://github.com/OpenVSLAM-Community/openvslam/blob/c5818b5fdeecf7cb4ae11d0589660862d5c570ef/src/openvslam/module/relocalizer.cc#L63

https://github.com/OpenVSLAM-Community/openvslam/blob/c5818b5fdeecf7cb4ae11d0589660862d5c570ef/src/openvslam/module/relocalizer.cc#L73

https://github.com/OpenVSLAM-Community/openvslam/blob/c5818b5fdeecf7cb4ae11d0589660862d5c570ef/src/openvslam/module/relocalizer.cc#L90

**Comment by ymd-stella** [comment]
> does the rough workflow documentation follows the format of the docs folder (.rst format) ?

Yes.

**Comment by jeffin07** [comment]
@ymd-stella  Can we close this issue or is there any more additions  ?

**Comment by ymd-stella** [comment]
No.
