### ISSUE TITLE
landmark and camera poses didn't have same coordinate?

### ISSUE THREAD

**Issue by fangxu622** [OpenVSLAM-Community/openvslam#171]
when I visualize the landmark( extract from msg file) and camera pose, they didn't in the same coordinate.  how to made them in one coordinate ?

 aist_living_lab1 example data 

![image](https://user-images.githubusercontent.com/16681534/135756024-ea000788-b762-471f-8410-af86b1b6289a.png)

**Comment by ymd-stella** [comment]
See https://github.com/OpenVSLAM-Community/openvslam/discussions/105
