### ISSUE TITLE
use_robust_matcher_for_relocalization_request

### ISSUE THREAD

**Issue by abylikhsanov** [OpenVSLAM-Community/openvslam#197]
Hi,

I have noticed your recent commit where you have included a new parameter:
`use_robust_matcher_for_relocalization_request`

Is there any documentation describing what does this parameter really do?

**Comment by ymd-stella** [comment]
Description is https://openvslam-community.readthedocs.io/en/latest/parameters.html#tracking.

> If true, use robust_matcher for relocalization request.

Do you need more information than this?
