### ISSUE TITLE
Merge bug fixes

### ISSUE THREAD

**Issue by ymd-stella** [OpenVSLAM-Community/openvslam#3]
This is a meta-ticket.
Some PRs have not been reviewed.
If you are willing to work on this, please choose a subtask and create an issue or a draft PR.

- [x] https://github.com/xdspacelab/openvslam/pull/339 (https://github.com/OpenVSLAM-Community/openvslam/issues/81)
- [x] https://github.com/xdspacelab/openvslam/pull/345
  - https://github.com/alvinsunyixiao/openvslam/commit/a9bab6da4f90229aa5dfbf73f32e0fca160b66de
- [x] https://github.com/xdspacelab/openvslam/pull/393
- [x] https://github.com/xdspacelab/openvslam/pull/408
  - https://github.com/yevsev/openvslam/commit/30273e6fb11bd18db227bfa6553621d97436eac5
- [x] https://github.com/xdspacelab/openvslam/pull/484
- [x] https://github.com/xdspacelab/openvslam/pull/514
- [x] https://github.com/xdspacelab/openvslam/pull/518
- [x] https://github.com/xdspacelab/openvslam/pull/519
  - https://github.com/alexdewar/openvslam/commit/1c8e7e3c3dbdaa83751f6c9681732b544d03ee3f

**Comment by mirellameelo** [comment]
Hi! Is this done or some still missing?

**Comment by ymd-stella** [comment]
If the item is not checked, it has not been merged.

**Comment by jeffin07** [comment]
Hi,
I would like to work on this.I  am  currently exploring openvslam using docker can you please guide me to work on this issue

**Comment by ymd-stella** [comment]
@jeffin07 I just checked, and there were only two left. I've added a link to the commit in the description, so please refer to it. The minimum you need to do is to apply these commits. It is also better if you can understand the cause of the problem and fix the areas where similar problems occur.
