### ISSUE TITLE
Timeline for IMU

### ISSUE THREAD

**Issue by oscarpang** [OpenVSLAM-Community/openvslam#63]
Thanks to all who contributed to this project. Also thanks for the community fork.

Is there a timeline for integrating the IMU functionality? Or a WIP branch? There are a number of cameras now equipped with the IMU(intel RealSense, StereoLab's Zed). 

Much thanks
Weiwu

**Comment by ymd-stella** [comment]
https://github.com/OpenVSLAM-Community/openvslam/tree/feat/imu

**Comment by ymd-stella** [comment]
My working branch is https://github.com/ymd-stella/openvslam-community/tree/wip/imu.
Contributions and comments are welcome.

**Comment by ymd-stella** [comment]
@oscarpang Did you get the information you needed?

**Comment by oscarpang** [comment]
Yes. Thanks so much!

**Comment by oscarpang** [comment]
@ymd-stella do you have a pointer to how to specify the transform from IMU to camera? Also, to specify the frequency of the IMU?

**Comment by oscarpang** [comment]
I actually found the example. Thanks again.
