### ISSUE TITLE
Add documentation for parameters

### ISSUE THREAD

**Issue by ymd-stella** [OpenVSLAM-Community/openvslam#87]
Draft is https://openvslam-community.readthedocs.io/en/latest/parameters.html

- [x] Camera
- [x] Feature
- [x] Mapping
- [x] Others
- [x] StereoRectifier
- [x] Initializer
- [x] PangolinViewer

**Comment by hitdshu** [comment]
Great job. Thanks for your excellent work in maintaining the community project.
